### PR TITLE
[no-jira] Attempt switch from Travis to GitHub Actions

### PR DESCRIPTION
**Pull request by knutsenm**

### CODE REVIEW

**Comment by knutsenm** [comment]
@jbirdjavi I'm baffled here. Somehow the Travis build runs the one test,

  https://app.travis-ci.com/github/CruGlobal/rails-infrastructure-canary/builds/242743050

yet the Action throws an error about a missing db/schema.rb file,

  https://github.com/CruGlobal/rails-infrastructure-canary/runs/4386372917

**Comment by knutsenm** [comment]
cc: @andrewroth

**Comment by jbirdjavi** [comment]
@knutsenm Sorry I really don't have the bandwidth to look into this currently.

**Comment by andrewroth** [comment]
Hmm well, there is no db/schema.rb present.. the error says something about limiting the frameworks present, is that an option?

**Comment by andrewroth** [comment]
I get the same error locally, and a touch db/schema.rb seems to get it past that. Can we just add an empty db/schema.rb?

**Comment by knutsenm** [comment]
> I get the same error locally, and a touch db/schema.rb seems to get it past that. Can we just add an empty db/schema.rb?

Sure, I'll try that, I'm just baffled how Travis manages it.

**Review by jbirdjavi — APPROVED** [review]
For normal apps, I'd probably prefer to remove ActiveRecord, but for this one, I agree with the solution since this is just a test app.

**Pull request merged**
