### PR TITLE
Add redis and sidekiq config

### PR DESCRIPTION
**Pull request by jbirdjavi**
Add redis/sidekiq config.

(Matt requested this in `#redis`, to test out new redis servers)

### CODE REVIEW

**Comment by jbirdjavi** [comment]
Tested as much as possible locally.  AWS secrets will need some values before deploy (redis and sidekiq creds).

**Comment by mattdrees** [comment]
awesome, thanks!

I'll add SIDEKIQ_CREDS. Same as what other rails apps use, right?

**Comment by jbirdjavi** [comment]
Yeah, SIDEKIQ_CREDS is the same as other apps.

Locally, I just used the rails console to fire off the test job, but feel free to add a controller. :)

**Comment by mattdrees** [comment]
ah, didn't know I could do that. Thanks!

**Pull request merged**
