### PR TITLE
Upgrade to Rails 6 w/ webpacker

### PR DESCRIPTION
**Pull request by jbirdjavi**

### CODE REVIEW

**Comment by jbirdjavi** [comment]
@mattdrees Do you still want to review changes I make to this app?  I made staging the default branch since jenkins won't build master anymore.

**Comment by mattdrees** [comment]
Sure, I'll still review changes.

Why won't jenkins build master anymore?

**Comment by mattdrees** [comment]
did you opt to use webpacker for practice? I don't think this project really does anything needing webpack.

**Comment by jbirdjavi** [comment]
@Omicron7 said that they took out some infrastructure necessary to be able to build master.

**Comment by jbirdjavi** [comment]
Yeah, Rails 6 uses webpacker by default instead of the older asset pipeline.  I wanted to iron out the kinks here before I started using it with other apps.

**Comment by mattdrees** [comment]
We can restore that infrastructure for testing of this. Would that be helpful?

**Comment by jbirdjavi** [comment]
Nah, I don't think it matters.  Jenkins built staging successfully, so I assume it would build master fine as well.  What would be helpful is being able to deploy to ECS, but I can test that on staging for a different app, so I don't really need it here.

**Comment by mattdrees** [comment]
It's only uncommenting out some code, so it's pretty easy on our side, and it'd enable deploying to ECS. I kinda want to verify that works ok anyway.

So I'll go ahead and do that.

**Comment by jbirdjavi** [comment]
Okay, sounds good :)

**Comment by Omicron7** [comment]
Stage should also already be deploying to ECS, should be available at `rails-canary-stage.aws.cru.org`
https://github.com/CruGlobal/cru-terraform/blob/master/applications/rails-infrastructure-canary/stage/application.tf#L8

**Comment by mattdrees** [comment]
I did have to manually set the service to 1 task instead of 0 tasks. But yeah, it's running there.

There is some kind of error, though, seemingly related to the asset pipeline - https://app.datadoghq.com/logs?cols=container_id&event&from_ts=1589320671421&index=main&live=false&messageDisplay=inline&query=service%3Arails-infrastructure-canary&stream_sort=desc&to_ts=1589320745574

**Comment by jbirdjavi** [comment]
What is the service called in ECS?  I'll check out the error later tonight or tomorrow and figure out a fix.

**Comment by mattdrees** [comment]
it's in the lab cluster (which is slightly confusing, sorry), named rails-infrastructure-canary-staging-app-sv3 - at https://console.aws.amazon.com/ecs/home?region=us-east-1#/clusters/lab/services/rails-infrastructure-canary-staging-app-sv3/details

**Pull request merged**
